name: Update JSON files

on:
  schedule:
    #Runs on January 7th
    - cron: '12 5 7 1 *' #12:12 AM / 1:12 AM U.S EST
    - cron: '12 11 7 1 *' #6:12 AM / 7:12 AM U.S EST
    - cron: '12 17 7 1 *' #12:12 PM / 1:12 PM U.S EST
    - cron: '12 23 7 1 *' #6:12 PM / 7:12 PM U.S EST
    
    - cron: '12 10 1 2-12 *' #12:12 AM / 1:12 AM U.S EST on first day of each month after January
    - cron: '42 6 8 12 *'  #testing purposes

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Website/backend/requirements.txt  #install dependencies listed in requirements.txt file

      - name: Run charts-yearly.py
        working-directory: ./Website/backend
        run: |
          python charts-yearly.py
          
      - name: Commit and push updated JSON files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Website/front-end/src/data/crashes_data_visualization.json
          git add Website/front-end/src/data/factors_vehicles_visualization.json
          git commit -m "Update JSON file"
          git push origin main
