name: Update JSON files

on:
  schedule:
    - cron: '12 5 1-7 * *'  #runs at 12:12 A.M U.S EST each day for the first week of each month

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Website/backend/requirements.txt  #install dependencies listed in requirements.txt file

      - name: Run charts-yearly.py
        working-directory: ./Website/backend
        run: |
          python charts-yearly.py
          
      - name: Commit and push updated JSON files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Website/front-end/src/data/crashes_data_visualization.json
          git add Website/front-end/src/data/vehicles_visualization.json
          git commit -m "Update JSON file"
          git push origin main
